// Generated by CoffeeScript 1.7.1
(function() {
  var Q, getAllProductUrls, phantom, _;

  _ = require('underscore');

  Q = require('q');

  phantom = require('phantom');

  phantom.create(function(ph) {
    return ph.createPage(function(page) {
      return page.open("http://www.welldressedwolf.com/", function(status) {
        if (status === "fail") {
          console.log("failed to load welldressedwolf. exiting.");
          ph.exit();
        }
        console.log("Ready to begin\n==============");
        page.evaluate(function() {
          console.log(document.title);
          return document.title;
        });
        return ph.exit();
      });
    });
  }, {
    dnodeOpts: {
      weak: false
    }
  });

  getAllProductUrls = function(page) {
    var unique_urls, urls, _getUrls;
    console.log(1);
    _getUrls = function() {
      var def;
      console.log(2);
      def = Q.defer();
      console.log("2.1");
      page.evaluate(function() {
        console.log("==", document.title);
        return document.title;
      }, function(result) {
        console.log("--", document.title);
        return def.resolve(result);
      });
      console.log(3);
      return def.promise;
    };
    console.log(4);
    _getUrls().then(function(title) {
      console.log(5);
      return console.log("got the title, " + title);
    });
    console.log(6);
    return;
    urls = $('.product a').map(function() {
      return $(this).attr('href');
    });
    urls = urls.toArray();
    unique_urls = [];
    urls.forEach(function(url) {
      if (!_.contains(unique_urls, url)) {
        return unique_urls.push(url);
      }
    });
    return unique_urls;
  };

}).call(this);
